export const gpButtonIcons = {
   'X': "✖",
   'O': "◯",
   'SQUARE': "▢",
   'TRIANGLE': "△",
   'L1': "L1",
   'L2': "L2",
   'R1': "R1",
   'R2': "R2",
   'SHARE': "⚟",
   'OPTIONS': "☰",
   'LEFT_STICK_PRESSED': "",
   'RIGHT_STICK_PRESSED': "",
   'CROSS_UP': "↑",
   'CROSS_DOWN': "↓",
   'CROSS_LEFT': "←",
   'CROSS_RIGHT': "→",
   'PS_LOGO': "PS",
   'TOUCH_PAD': "",
}
