export const gpButtonIcons = {
   X: "✖",
   O: "◯",
   SQUARE: "▢",
   TRIANGLE: "△",
   CROSS_UP: "↑",
   CROSS_DOWN: "↓",
   CROSS_LEFT: "←",
   CROSS_RIGHT: "→",
   L1: "L1",
   L2: "L2",
   R1: "R1",
   R2: "R2",
   SHARE: "⚟",
   OPTIONS: "☰",
   PS_LOGO: "PS",
   LEFT_STICK_PRESSED: "",
   RIGHT_STICK_PRESSED: "",
   TOUCH_PAD: "",
}