export const gpButtonMap = {
   'X': 0,
   'O': 1,
   'SQUARE': 2,
   'TRIANGLE': 3,
   'L1': 4,
   'R1': 5,
   'L2': 6,
   'R2': 7,
   'SHARE': 8,
   'OPTIONS': 9,
   'LEFT_STICK_PRESSED': 10,
   'RIGHT_STICK_PRESSED': 11,
   'CROSS_UP': 12,  
   'CROSS_DOWN': 13,    
   'CROSS_LEFT': 14,
   'CROSS_RIGHT': 15,
   'PS_LOGO': 16,
   'TOUCH_PAD': 17,
}